name: MDBOOK DOCKER

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKER_USER }}/mdbook:latest .
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USER }}/mdbook:latest
      
