name: MDBOOK DOCKER
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build
      run: docker build -t mdbook . --no-cache
    - name: Tag   
      run: docker tag mdbook ${{ secrets.DOCKERHUB_USERNAME }}/mdbook:latest
    - name: Push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mdbook:latest